# Generated by Django 4.2.14 on 2024-08-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrochart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='firebase_uid',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
