# Generated by Django 4.2.14 on 2024-09-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrochart', '0002_react_firebase_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
