# Generated by Django 4.2.13 on 2024-09-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrochart', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='firebase_uid',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
