# Generated by Django 4.2.13 on 2024-09-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrochart', '0006_alter_react_firebase_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
