# Generated by Django 4.2.13 on 2024-09-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrochart', '0007_userprofile_is_active_userprofile_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='firebase_uid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
