# Generated by Django 4.2.13 on 2024-09-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrochart', '0008_alter_react_firebase_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(max_length=255, null=True)),
                ('birth_date', models.DateField()),
                ('birth_time', models.TimeField()),
                ('birth_location', models.CharField(max_length=255)),
                ('transit_start_date', models.DateField()),
                ('transit_end_date', models.DateField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
