# Generated by Django 4.2.13 on 2024-09-17 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astrochart', '0010_remove_transitchart_firebase_uid_transitchart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitchart',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
