# Generated by Django 4.1.4 on 2024-05-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_customer_e_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoroscopeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('zodiac_sign', models.CharField(max_length=20)),
            ],
        ),
    ]
