# Generated by Django 4.1.4 on 2024-05-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_alter_horoscopesubscription_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horoscopesubscription',
            name='zodiac_sign',
            field=models.CharField(choices=[('aries', '♈ Bélier'), ('taurus', '♉ Taureau'), ('gemini', '♊ Gémeaux'), ('cancer', '♋ Cancer'), ('leo', '♌ Lion'), ('virgo', '♍ Vierge'), ('libra', '♎ Balance'), ('scorpio', '♏ Scorpion'), ('sagittarius', '♐ Sagittaire'), ('capricorn', '♑ Capricorne'), ('aquarius', '♒ Verseau'), ('pisces', '♓ Poissons')], max_length=20),
        ),
    ]
